version: 2

jobs:
  build:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo
    steps:
        - checkout
        - restore_cache:
            keys:
              - v1-dependencies-{{ checksum "package.json" }}
              - v1-dependencies-
        - run: npm install
        - run: npm run lint
        - save_cache:
            paths:
              - node_modules
            key: v1-dependencies-{{ checksum "package.json" }}
        - run: npm test
        - run:
            name: 'Runing test'
            command: |
              mkdir ~/repo/junit
              ./node_modules/mocha/bin/mocha test --recursive --timeout=10000 --exit --reporter mocha-junit-reporter --reporter-options mochaFile=./junit/results.xml
            when: always
        - run:
            name: eslint
            command: |
                ./node_modules/.bin/eslint ./ --format junit --output-file ./reports/eslint/eslint.xml
            when: always
        - store_test_results:
            path: ~/repo/junit/
        - store_artifacts:
            path: ~/repo/junit

  deploy-stage:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo
    steps:
        - checkout
        - restore_cache:
            keys:
              - v1-dependencies-{{ checksum "package.json" }}
              - v1-dependencies-
        - run:
            name: Authenticate with registry
            command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/repo/.npmrc
        - deploy:
            name: Publish package
            command: npm publish --tag beta
            filters:
              branches:
                only:
                  - master

  deploy-prod:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo
    steps:
        - checkout
        - restore_cache:
            keys:
              - v1-dependencies-{{ checksum "package.json" }}
              - v1-dependencies-
        - run:
            name: Authenticate with registry
            command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/repo/.npmrc
        - deploy:
            name: Publish package
            command: npm publish
            filters:
              branches:
                only:
                  - master
workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: /feature-.*/
              ignore:
                - develop
      - deploy-stage:
          requires:
            - build
          filters:
            branches:
              only: staging
      - deploy-prod:
          requires:
            - build
          filters:
            branches:
              only: master
